# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "stretch64"

  config.vm.hostname = "node01" 
  config.vm.network "private_network", ip: "10.10.10.101"
  config.vm.post_up_message = "docker machine node01" 

  # config.vm.synced_folder "data/" 

  config.vm.provider "virtualbox" do |vb|    
    vb.gui = false
    vb.name = "Docker cluster NODE01"
    vb.memory = "1024"
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
   end

  # config.vm.provision   "ansible_local" do |ansible|
  #    ansible.playbook = "provisioning/playbook.yml"
  # end 
end
